version: '3.8'

services:
  redis:
    image: docker.io/valkey/valkey:8.0.2
    container_name: api_gateway_redis
    ports:
      - "6379:6379"
    restart: always

  postgres:
    image: docker.io/postgres:17.2
    container_name: api_gateway_postgres
    restart: always
    environment:
      POSTGRES_USER: api_user
      POSTGRES_PASSWORD: api_password
      POSTGRES_DB: api_observability
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
